version: '3'
services:
  hello_node:
    image: "peke2/hello_node_server:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hello_node_server"
    depends_on:
      - hello_node_db
    ports:
      - 3000:3000
    links:
      - hello_node_db:database 
  hello_node_db:
    image: "mysql:5.7.17"
    container_name: "hello_node_db"
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - /tmp/db/helllo_node_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
