apiVersion: v1
kind: Service
metadata:
  name: hello-lb
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3001
      targetPort: 3000
      #nodePort: 30082
  selector:
    app: hello-node