apiVersion: v1
kind: Service
metadata:
  namespace: hello
  name: hello-mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database
        image: mysql:5.7.17
        env:
        - name: MYSQL_USER
          value: 'root'
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        - name: MYSQL_PASSWORD
          value: 'pass'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hello
  name: mysql-pv
  labels:
    type: local
spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
    hostPath:
      path: "/tmp/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hello
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
