# 管理の関連は以下
# Deployment -> Replicaset -> Pod
# ロールバックやローリングアップデートなども管理してくれるため Replicaset よりも利便性は高い？

apiVersion: v1
kind: Service
metadata:
  namespace: hello
  name: hello-node-service
spec:
  selector:
    app: hello-node
  type: ClusterIP
  ports:
  - port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: node-container
          image: localhost:5000/peke2/hello_node_server
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_ROOT_PASSWORD
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'pass'
