# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-lb
#   namespace: hello
# spec:
#   type: LoadBalancer
#   ports:
#     - name: "http-port"
#       protocol: "TCP"
#       port: 3001
#       targetPort: 3000
#       #nodePort: 30082
#   selector:
#     app: hello-node

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: hello
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hello-node-service
          servicePort: 3000

